---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: fedora
    image: docker.io/pycontribs/fedora:latest
    pre_build_image: true
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: centos8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8 --exclude .venv/
provisioner:
  name: ansible
verifier:
  name: ansible
